### ISSUE TITLE
Jan 04, 2016 9:42:03 PM controlP5.ControlBroadcaster printMethodErro

### ISSUE THREAD

**Issue by bvernham** [sojamo/controlp5#39] opened 2016-01-05 02:54 UTC
Jan 04, 2016 9:42:03 PM controlP5.ControlBroadcaster printMethodError
SEVERE: An error occured while forwarding a Controller event, please check your code at Toggle_AM
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
	at controlP5.ControlBroadcaster.callTarget(Unknown Source)
	at controlP5.ControlBroadcaster.broadcast(Unknown Source)
	at controlP5.Controller.broadcast(Unknown Source)
	at controlP5.Button.setValue(Unknown Source)
	at PID_FrontEnd_v03.setup(PID_FrontEnd_v03.java:133)
	at processing.core.PApplet.handleDraw(PApplet.java:2374)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
Caused by: java.lang.NullPointerException
	at PID_FrontEnd_v03.Toggle_AM(PID_FrontEnd_v03.java:386)
	... 13 more
[PID_FrontEnd_v03.zip](https://github.com/sojamo/controlp5/files/77955/PID_FrontEnd_v03.zip)

**Comment by sojamo** [comment] 2016-01-05 03:04
well, please check your code, there is a NullPointerException caused by your code.

> Caused by: java.lang.NullPointerException
at PID_FrontEnd_v03.Toggle_AM(PID_FrontEnd_v03.java:386)

**Comment by sojamo** [comment] 2016-02-14 11:36
since there was no follow up, closing issue.

**Closed by sojamo** 2016-02-14 11:36 UTC
